name: "Upload KAALAKIOTA"

on:
  push:
    paths:
      - "KAALAKIOTA/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 3035615398
          publishedFileID: CHANGEME
          path: KAALAKIOTA
          changelog: ${{ github.event.head_commit.message }}              
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
