name: "Upload SAIDS_EWAR"

on:
  push:
    paths:
      - "SAIDS_EWAR/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: 3026263372
          path: SAIDS_EWAR
          changelog: ${{ github.event.head_commit.message }}              
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
