name: "Upload SpaceAIDS ShipCore Config"

on:
  push:
    paths:
      - "SAIDS_EpsteinDrives/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: 3042817886
          path: "SAIDS_EpsteinDrives"
          changelog: ${{ github.event.head_commit.message }}              
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
